### ISSUE TITLE
Add phpstan to dev dependencies and configure to run on Travis CI

### ISSUE THREAD

**Issue by ramsey** [ramsey/collection#20]
Refer to https://github.com/phpstan/phpstan

Depends on #14

**Comment by adioe3** [comment]
I'd like to take care of this. Have you also considered adding [phan](https://github.com/phan/phan) to the mix?

**Comment by ramsey** [comment]
What does phan provide in addition to phpstan?

**Comment by AkshatSrivastava2** [comment]
I am working on this issue. Ref: #35
