### ISSUE TITLE
Add scripts to composer.json for lint, phpcs, and phpunit

### ISSUE THREAD

**Issue by ramsey** [ramsey/collection#21]
Refer to [composer.json in ramsey/uuid](https://github.com/ramsey/uuid/blob/962b14cf35602226466f50241a92395b6fc4a7aa/composer.json#L60-L74) for an example.

**Comment by blanxii** [comment]
Added the scripts, also changed some code to have phpstan working, but will crash on travis <7.0 php versions, check:

`PHPStan requires PHP >= 7.1. You have to run it in environment with PHP 7.x but the actual code does not have to use PHP 7.x features. (Code written for PHP 5.6 and earlier can run on 7.x mostly unmodified.)`

What do you want to do in this case?

**Comment by ramsey** [comment]
Please check the pull requests to make sure this work hasn't already been done. I'll merge in a bunch of this later today. https://github.com/ramsey/collection/pulls
