### ISSUE TITLE
Call functions with global namespace

### ISSUE THREAD

**Issue by icanhazstring** [ramsey/collection#46]
In my PR #44 I got feed back to use global namespace function calls . There are two things we can do here.

1. Opcode optimizations
For example: `\is_array` instead of `is_array`.
There is a list of functions that have an opcode benefit from those optimizations.
@see https://github.com/php/php-src/blob/master/Zend/zend_compile.c#L3803

2. Minor speed advantage without opcode change
Others might only have a minor advantage in speed like: `\array_merge` vs `array_merge`
There is a benchmark comparing the global namespace call vs the function lookup
@see http://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

There a many repositories who already have this implemented.
Like PHP-CS-Fixer (https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048)

> Which might be a good addition to this repository to simply keep everything in check an even set the global namespace call for functions.

---

Since I didn't want to change the whole implementation with the mentioned PR I simply propose this here and would also file a PR if necessary.

**Comment by ramsey** [comment]
I'm fine with explicitly calling global functions with the global namespace. I think there's an argument to be made for consistency. Feel free to open a PR for this. 😄

**Comment by icanhazstring** [comment]
Will do. You can assign it to me then ;)
