### ISSUE TITLE
TypedMap class

### ISSUE THREAD

**Issue by eclipxe13** [ramsey/collection#5]
I'm interested on push the `TypedMap` class, is like a Map but keys and values are typed. This would follow the generics mimics of `Map<K key, V value>`

You could use the concrete class directly:

```php
$map = new TypedMap('string', \My\Foo::class, $data);
$map['foo'] = new \My\Foo();

// this throw an exception since key is not a string
$map[1] = new \My\Foo();

// this throw an exception since value stdClass is not a \My\Foo
$map['baz'] = new \stdClass()
```

Or extending the AbstractTypedMap:

```php
class FooTypedMap extends AbstractTypedMap
{
    public function getKeyType()
    {
        return "int"
    }

    public function getValueType()
    {
         return Foo::class;
    }
}

$map = new FooTypedMap([
    100 => new Foo(),
    200 => new Foo(2),
]);
```

Question: Should I place the class inside src/Map? Looks like this is the place of Maps since it contains the concrete class `NamedParameterMap`.
As this contains the interface, an abstract class and a concrete implementation looks more organized on its own namespace `Ramsey\Collection\TypedMap` that points to `src/TypedMap`.

Thanks and please advice.

**Comment by ramsey** [comment]
If the TypedMap implements the MapInterface, then I think it should stay within the `Ramsey\Collection\Map` namespace, but if it's completely separate, then a new `Ramsey\Collection\TypedMap` namespace is fine.

**Comment by eclipxe13** [comment]
PR #8 was submitted, please take a look

**Comment by ramsey** [comment]
All looks great. I like the changes you're adding. Your work is much appreciated. Feel free to add yourself to the "team members" in CONTRIBUTING.md and to the authors in composer.json. :-)
