### ISSUE TITLE
ramsey/collection requires abandoned projects

### ISSUE THREAD

**Issue by sloanja** [ramsey/collection#58]
ramsey/collection requires packages in composer.json which have been marked as abandonded by the author as of 20 days ago (March 15, 2020):
jakub-onderka/php-parallel-lint (see https://github.com/JakubOnderka/PHP-Parallel-Lint)

Recommended replacements:
https://github.com/php-parallel-lint/PHP-Parallel-Lint

I found this issue by loading up a new fresh copy of Laravel and it was complaining about the abandoned packages right away.

**Comment by ramsey** [comment]
Thanks for reporting! I appreciate it.

I don't see this as a bug, since it doesn't break anything, and there are no errors. It is something that's on my list of things to clean up as regular project maintenance, so I will prioritize it higher on the list.

**Comment by SuguruOoki** [comment]
> https://packagist.org/packages/jakub-onderka/php-parallel-lint

I saw this link, and as @sloanja writes, it's abandoned In php-parallel-lint/php-parallel-lint, there seems to be a I think I'm going to have to replace it, can I submit a pull request?

**Comment by ramsey** [comment]
Certainly! Feel free to do so. Thanks! 😀
