### ISSUE TITLE
[Proposal] Typed Queue

### ISSUE THREAD

**Issue by zf2timo** [ramsey/collection#6]
I use in a Project the Collection Class with a Entity as Type. This work really good and is really straightforward. 
But i think a Queue (FIFO Principle) would match my needs even better.

Therefore, my consideration of whether it is a good extension for this project.
Is this a benefit for this Project?

**Comment by ramsey** [comment]
I think it's a great addition for this project, given that the project aims to bring much of the functionality of the Java Collection library to PHP userland, and the Java Collection library provides a Queue: http://docs.oracle.com/javase/8/docs/api/java/util/Queue.html

Thanks!

**Comment by zf2timo** [comment]
Great. I will send a PR.

**Comment by ramsey** [comment]
Thanks!
