### ISSUE TITLE
Map not working in String Collection 

### ISSUE THREAD

**Issue by et-nik** [ramsey/collection#62]
`map` method in `AbstractCollection` not working for Collection with type `string`
https://github.com/ramsey/collection/blob/master/src/AbstractCollection.php#L261

I have StringCollection
```php
class StringCollection extends AbstractCollection
{
    public function getType(): string
    {
        return 'string';
    }
}
```

`map` method doesn't work when I want to change elements case.

```php
$stringCollection = new StringCollection(['foo', 'bar']);

$upperStringCollection = $stringCollection->map(function($item) {
    return strtoupper($item);
}); 

print_r($upperStringCollection->toArray());
```

## Expected `$upperStringCollection` value

```
Array
(
    [0] => FOO
    [1] => BAR
)
```

## Actual `$upperStringCollection` value

```
Array
(
    [0] => foo
    [1] => bar
)
```

**Comment by ramsey** [comment]
Great catch! Thank you for reporting this!
