### ISSUE TITLE
Merging sets does not remove duplicates

### ISSUE THREAD

**Issue by Lehren** [ramsey/collection#84]
## Description
If you merge a Set containing [X, Y] with a Set containing [Y, Z], the result Set will be [X, Y, Y, Z]. Which is incorrect.

## Steps to reproduce

1. Run the following code
```
$set1 = new Set('string', ['X', 'Y']);
$set2 = new Set('string', ['Y', 'Z']);
$set3 = $set1->merge($set2);
foreach($set3 as $el)
{
    echo($el . "\n");
}

```

2. See how element 'Y' occurs twice.

## Expected behavior
Element 'Y' should only occur once in `set3`

## Screenshots or output
PHPStorm inspector output
![Schermafbeelding 2021-10-07 om 11 37 51](https://user-images.githubusercontent.com/8881212/136359711-9577d5bc-29e4-46da-a385-287978825802.png)

## Environment details

- version of this package: *1.1.3*
- PHP version: *7.4.16*
- OS: *macOS Big Sur (11.6)*

**Comment by ramsey** [comment]
Thanks for reporting this! I've fixed it in version 1.2.2.
