### ISSUE TITLE
New release, please?

### ISSUE THREAD

**Issue by flavioheleno** [ramsey/collection#92]
Hi! First and foremost, thanks for such an amazing library! I love it <3

There has been a PR (#87) that was merged past October, but a new release has not been done yet.

I don't want to be a PITA, but could we pretty please get a new revision?

Thank you again! :-D

**Comment by TheMY3** [comment]
@ramsey can you do it please? =)

**Comment by ramsey** [comment]
I've just tagged version 2.0.0, which includes #87. Sorry for the delay!
